
- name: Install packages and manage service on Linux
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Install packages on RedHat family
      yum:
        name:
          - vim
          - htop
          - git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install packages on Debian family
      apt:
        name:
          - vim
          - htop
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      
      - 
      -name: install and configure tomcat web server
       hosts: web 
       become: yes
       
       vars:
          tomcat_port: 8080

      -name: install and configure Apache web server
        hosts: web
        become: yes

        roles:
          - httpd
          - tomcat
